name: Test workflow

on: push

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install package
        run: pip install .
      - name: Install pytest
        run: pip install pytest
      - name: Run unit tests
        run: pytest
