name: Test workflow

on: push

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create conda environment
        run: conda env create -y -n testenv -f conda.yaml && conda activate testenv && conda list
      - name: Install package
        run: pip install .
      - name: Install pytest
        run: pip install pytest
      - name: Run unit tests
        run: pytest
