name: Test workflow

on: push

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Update apt-get
        run: sudo apt-get update
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.515
      - name: Create conda environment
        run: conda env create -y -n testenv -f conda.yaml
      - name: Dump conda environment
        run: conda list -n testenv
      - name: Install package
        run: conda run -n testenv pip install .
      - name: Install pytest
        run: conda run -n testenv pip install pytest
      - name: Run unit tests
        run: conda run -n testenv pytest
